version: '3'
services:
  web:
    image: node:current
    command: npm run-script run
    ports:
     - "3000:3000"
     - "9229:9229"
    depends_on: [database, mail]
    user: "node"
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - ./var/lib/postgresql:/var/lib/postgresql/data
#  redis:
#    image: redis:latest
#    command: ["redis-server", "--appendonly", "yes"]
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./devops/redis:/data
  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"